### ISSUE TITLE
"

### ISSUE THREAD

**Issue by antoscha** [NVIDIA/Eigensolver_gpu#1]
If the main GCC compiler has version > 6, following error occurs:
`error: #error -- unsupported GNU version! gcc versions later than 6 are not supported!`

**Comment by romerojosh** [comment]
The dependency with the GCC compiler is introduced with the `nollvm` option provided in the `FLAGS2` and `FLAGS3` variables in `Makefile`. 

What version of the PGI compiler are you using? If using a recent version (v17.10), this option can be removed and this should be resolved. Can you try removing the `nollvm` options from the `Makefile` and see if it compiles?

**Comment by antoscha** [comment]
Now works well. Many thanks!

**Comment by romerojosh** [comment]
Great!
