### ISSUE TITLE
Mistake in documentation

### ISSUE THREAD

**Issue by bonfus** [NVIDIA/Eigensolver_gpu#2]
I believe that the following indication is erroneous:

https://github.com/NVIDIA/Eigensolver_gpu/blob/d8358431068a9d6a861a1d30ff0bd8f492334b5b/lib_eigsolve/zhegvdx_gpu.F90#L68

During the diagonalization, at the following line:

https://github.com/NVIDIA/Eigensolver_gpu/blob/d8358431068a9d6a861a1d30ff0bd8f492334b5b/lib_eigsolve/zheevd_gpu.F90#L101

Z_h is expected to be (lda, N) according to this document: https://linux.die.net/man/l/zstedc .

Correct?

**Comment by romerojosh** [comment]
Thanks for catching this error! The `iu - il +1` dimension was actually incorrectly stated for both the eigenvector and eigenvalue arrays and has been fixed in commit b195ce9.
